name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-uv-pip-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv

      - name: Create virtual environment
        run: |
          uv venv

      - name: Install dependencies with uv
        run: |
          uv pip install ."[tests]"

      - name: Run tests
        run: |
          uv run pytest
  
  test-pip-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.14']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with pip
        run: |
          pip install ."[tests]"

      - name: Run tests
        run: |
          pytest